export const clubs = [
  {
    _id: "club-1",
    name: "CodeForge Club",
    description: "A community of developers building practical tech products and hackathon solutions.",
    department: "Technology",
    hostedEvents: 14,
  },
  {
    _id: "club-2",
    name: "BizCatalyst Society",
    description: "Fostering leadership, entrepreneurship, and strategic thinking across campus.",
    department: "Management",
    hostedEvents: 10,
  },
  {
    _id: "club-3",
    name: "SciQuest Circle",
    description: "Science enthusiasts exploring research talks, innovation labs, and project showcases.",
    department: "Science",
    hostedEvents: 8,
  },
];

export const events = [
  {
    _id: "event-1",
    title: "AI Product Hackathon 2026",
    description: "Build AI-powered products with mentors, workshops, and final stage pitching.",
    department: "Technology",
    type: "hackathon",
    date: "2026-05-10",
    time: "09:00 AM",
    venue: "Innovation Lab, Block C",
    organizer: "CodeForge Club",
    tags: ["AI", "Hackathon", "Product"],
    bannerImage: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
    interestedCount: 148,
    trending: true,
  },
  {
    _id: "event-2",
    title: "Startup Finance Masterclass",
    description: "Understand startup budgeting, runway planning, and investor communication basics.",
    department: "Management",
    type: "seminar",
    date: "2026-05-08",
    time: "02:00 PM",
    venue: "Seminar Hall 2",
    organizer: "BizCatalyst Society",
    tags: ["Finance", "Startup", "Business"],
    bannerImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
    interestedCount: 86,
    trending: true,
  },
  {
    _id: "event-3",
    title: "Robotics Workshop: Build & Control",
    description: "Hands-on robotics session covering sensors, actuators, and autonomous control loops.",
    department: "Technology",
    type: "workshop",
    date: "2026-05-14",
    time: "11:00 AM",
    venue: "Mechanical Workshop Lab",
    organizer: "CodeForge Club",
    tags: ["Robotics", "Workshop"],
    bannerImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    interestedCount: 63,
    trending: false,
  },
  {
    _id: "event-4",
    title: "Campus Cultural Fest Ignite",
    description: "A high-energy fest with performances, stalls, competitions, and celebrity night.",
    department: "General",
    type: "fest",
    date: "2026-05-20",
    time: "05:00 PM",
    venue: "Open Air Theater",
    organizer: "University Cultural Council",
    tags: ["Fest", "Culture", "Performance"],
    bannerImage: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80",
    interestedCount: 312,
    trending: true,
  },
  {
    _id: "event-5",
    title: "Biotech Research Poster Showcase",
    description: "Students present applied biotech research projects with peer and faculty feedback.",
    department: "Science",
    type: "seminar",
    date: "2026-04-20",
    time: "10:30 AM",
    venue: "Biotech Department Gallery",
    organizer: "SciQuest Circle",
    tags: ["Science", "Research", "Poster"],
    bannerImage: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    interestedCount: 44,
    trending: false,
  },
];
